### ISSUE TITLE
Not installing in 2.8 due to missing comma in bl_info  dictionary after the "wiki_url" key: value pair

### ISSUE THREAD

**Issue by simucentral** [tomlechner/blender-stuff#1]
Not installing in 2.8 due to missing comma in bl_info  dictionary after the "wiki_url" key: value pair, before "tracker_url" key: value pair.
Please update the code

Btw, thankyou so much for the code.

**Comment by tomlechner** [comment]
Ahhhh.. sorry this slipped past me till now! Just added a version that should work with 2.80 and up. Though I've only tested on 2.82.
